export const GET_DASHBOARD_INFO_LOADING = 'GET_DASHBOARD_INFO_LOADING'
export const GET_DASHBOARD_INFO_SUCCESS = 'GET_DASHBOARD_INFO_SUCCESS'
export const GET_DASHBOARD_INFO_FAILURE = 'GET_DASHBOARD_INFO_FAILURE'