export const GET_ORDERS_INFO_LOADING = 'GET_ORDERS_INFO_LOADING'
export const GET_ORDERS_INFO_SUCCESS = 'GET_ORDERS_INFO_SUCCESS'
export const GET_ORDERS_INFO_FAILURE = 'GET_ORDERS_INFO_FAILURE'

export const UPDATE_ORDER_INFO_LOADING = 'UPDATE_ORDER_INFO_LOADING'
export const UPDATE_ORDER_INFO_SUCCESS = 'UPDATE_ORDER_INFO_SUCCESS'
export const UPDATE_ORDER_INFO_FAILURE = 'UPDATE_ORDER_INFO_FAILURE'