export const GET_INVENTORY_INFO_LOADING = 'GET_INVENTORY_INFO_LOADING'
export const GET_INVENTORY_INFO_SUCCESS = 'GET_INVENTORY_INFO_SUCCESS'
export const GET_INVENTORY_INFO_FAILURE = 'GET_INVENTORY_INFO_FAILURE'

export const ADD_INVENTORY_INFO_LOADING = 'ADD_INVENTORY_INFO_LOADING'
export const ADD_INVENTORY_INFO_SUCCESS = 'ADD_INVENTORY_INFO_SUCCESS'
export const ADD_INVENTORY_INFO_FAILURE = 'ADD_INVENTORY_INFO_FAILURE'