export const GET_PAYMENTS_INFO_LOADING = 'GET_PAYMENTS_INFO_LOADING'
export const GET_PAYMENTS_INFO_SUCCESS = 'GET_PAYMENTS_INFO_SUCCESS'
export const GET_PAYMENTS_INFO_FAILURE = 'GET_PAYMENTS_INFO_FAILURE'