export const GET_USERS_INFO_LOADING = 'GET_USERS_INFO_LOADING'
export const GET_USERS_INFO_SUCCESS = 'GET_USERS_INFO_SUCCESS'
export const GET_USERS_INFO_FAILURE = 'GET_USERS_INFO_FAILURE'

export const ADD_USER_INFO_LOADING = 'ADD_USER_INFO_LOADING'
export const ADD_USER_INFO_SUCCESS = 'ADD_USER_INFO_SUCCESS'
export const ADD_USER_INFO_FAILURE = 'ADD_USER_INFO_FAILURE'

// export const UPDATE_USER_INFO_LOADING = 'UPDATE_USER_INFO_LOADING'
// export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'
// export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE'

// export const DELETE_USER_INFO_LOADING = 'DELETE_USER_INFO_LOADING'
// export const DELETE_USER_INFO_SUCCESS = 'DELETE_USER_INFO_SUCCESS'
// export const DELETE_USER_INFO_FAILURE = 'DELETE_USER_INFO_FAILURE'