export const GET_BRAND_INFO_LOADING = 'GET_BRAND_INFO_LOADING'
export const GET_BRAND_INFO_SUCCESS = 'GET_BRAND_INFO_SUCCESS'
export const GET_BRAND_INFO_FAILURE = 'GET_BRAND_INFO_FAILURE'

export const ADD_BRAND_INFO_LOADING = 'ADD_BRAND_INFO_LOADING'
export const ADD_BRAND_INFO_SUCCESS = 'ADD_BRAND_INFO_SUCCESS'
export const ADD_BRAND_INFO_FAILURE = 'ADD_BRAND_INFO_FAILURE'

export const UPDATE_BRAND_INFO_LOADING = 'UPDATE_BRAND_INFO_LOADING'
export const UPDATE_BRAND_INFO_SUCCESS = 'UPDATE_BRAND_INFO_SUCCESS'
export const UPDATE_BRAND_INFO_FAILURE = 'UPDATE_BRAND_INFO_FAILURE'

export const DELETE_BRAND_INFO_LOADING = 'DELETE_BRAND_INFO_LOADING'
export const DELETE_BRAND_INFO_SUCCESS = 'DELETE_BRAND_INFO_SUCCESS'
export const DELETE_BRAND_INFO_FAILURE = 'DELETE_BRAND_INFO_FAILURE'